// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('init-test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('init-test', async function() {
    await driver.get("https://www.balatonapartmanok.hu/")
    // await driver.manage().window().setRect({ width: 1436, height: 875 })
    // await driver.findElement(By.id("btnPiros")).click()
    // await driver.findElement(By.css(".mb-3 .btn-red-rounded")).click()
    // await driver.findElement(By.id("dropdownMenuButton")).click()
    // await driver.findElement(By.css(".en")).click()
    // await driver.findElement(By.linkText("Request an Offer")).click()
    // await driver.findElement(By.css("#dropdownMenuButton > .mr-2")).click()
    // await driver.findElement(By.css(".hu > .mr-2")).click()
  })
})
